### ISSUE TITLE
Does this support the Windows platform?

### ISSUE THREAD

**Issue by untyper** [a-n-t-h-o-n-y/TermOx#44]
^

**Comment by tvb377** [comment]
I have it running under windows using PDCurses and VC++.
Only minimal changes were required.

I'm using a version of CPPurses that is roughly six months old. This only as a hint that I don't know what has happened in the master branch since then.

Is a port to Windows an interesting goal for this project?
Then I would try to find spare time to post some pull requests.

BR,
Titus

**Comment by a-n-t-h-o-n-y** [comment]
I don't have experience developing on Windows, so it isn't a goal of mine at the moment. The library has had significant changes under the hood and no longer relies on ncurses, so using pdcurses would not work with newer versions.

The [Escape](https://github.com/a-n-t-h-o-n-y/Escape) library is now used for the reading and writing to the terminal, and there are some unix specific calls in there, but it might not take too much effort to wrap those in `ifdef`s for someone who knows the Windows platform. This is assuming the escape sequences are the same for the Windows terminal.
