### ISSUE TITLE
CPPurses for Windows porting

### ISSUE THREAD

**Issue by chaolinyu** [a-n-t-h-o-n-y/TermOx#7]
Anthony,
   It is very exciting to discover this project which meet our needs. We found this project is very good to use modern project for TUI (C++14). We would like to use it but we are stocked at Windows porting.
It would be nice if these following OS can be supported. 
Microsoft Windows and FreeBSD/Solaris?

**Comment by a-n-t-h-o-n-y** [comment]
Hi, glad you are interested in the project. The project is Linux only at the moment because it relies on the ncurses library and one system call for window resizing. It looks like FreeBSD and Solaris have access to this library but I have not tested either, I'm away from my computer for the next week. It looks like PDCurses might work for Windows support, I'd be interested in getting this working but It's not something I would be able to work on for a while.
If you are interested there are only a few files that rely on system specific calls, and it looks like PDCurses has a similar interface to ncurses, so it might not be too difficult to make a fork and get it working. These files are:
ncurses_paint_engine.cpp
ncurses_event_listener.cpp
terminal_resize_event.cpp
terminal_properties.cpp

**Comment by LoganDark** [comment]
Use WSL lmao

**Comment by a-n-t-h-o-n-y** [comment]
@LoganDark Good point, though this only gets you half-way there, if you want any Windows specific libraries or code to work with your TUI you are out of luck.

**Comment by LoganDark** [comment]
@a-n-t-h-o-n-y You could use IPC

**Comment by a-n-t-h-o-n-y** [comment]
Updating this to point to the [Escape](https://github.com/a-n-t-h-o-n-y/Escape) library, most windows porting work needs to happen at this lower level, now that ncurses is no longer a dependency.

**Comment by chaolinyu** [comment]
Does this mean Windows support is okay now for TermOx?

**Comment by a-n-t-h-o-n-y** [comment]
Not yet, just that the Linux specific code moved into the Escape library, but if the Escape library is updated for windows support, then TermOx will also have Windows support, I believe.
